sudo: false

before_install:
  - git clone --depth=50 --branch=master git://github.com/visibilityspots/puppet-jetty.git visibilityspots/jetty

cache:
  - apt
  - bundler

addons:
  apt:
    packages:
    - rpm

rvm:
  - 1.9.3

env:
  - PUPPET_VERSION=3.8.1

script:
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/remove-previous-package.sh | bash -s
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/package-puppet-module.sh | bash -s jetty development
  - bundle exec package_cloud push visibilityspots/puppet-development-modules/el/6 *.rpm

notifications:
  email:
    - travis@visibilityspots.com
