sudo: false

cache:
  - apt
  - bundler

addons:
  apt:
    packages:
    - rpm

rvm:
  - 1.9.3

env:
  - PUPPET_VERSION=3.8.1

script:
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/remove-previous-package.sh | bash -s
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/package-puppet-module.sh | bash -s jetty development
  - package_cloud push visibilityspots/puppet-development-modules/el/6 *.rpm

notifications:
  email:
    - travis@visibilityspots.com
