sudo: false

before_install:
  - ln -s . jetty

cache:
  - apt
  - bundler

addons:
  apt:
    packages:
    - rpm

rvm:
  - 1.9.3

script:
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/puppet-lintian-validation.sh | bash -s jetty
  - lint_state=$?
  - curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/puppet-syntax-validation.sh | bash -s jetty
  - syntax_state=$?
  - if [ $lint_state -eq 0 ] && [ $syntax_state -eq 0 ]; then curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/remove-previous-package.sh | bash -s; fi
  - if [ $lint_state -eq 0 ] && [ $syntax_state -eq 0 ]; then curl -s https://raw.githubusercontent.com/visibilityspots/ci-scripts/master/puppet/package-puppet-module.sh | bash -s jetty development; fi
  - if [ $lint_state -eq 0 ] && [ $syntax_state -eq 0 ]; then bundle exec package_cloud push visibilityspots/puppet-development-modules/el/6 *.rpm; fi

notifications:
  email:
    - travis@visibilityspots.com
